### ISSUE TITLE
Blocked a frame with origin ... from accessing a cross-origin frame. at https://cdn.rawgit.com/

### ISSUE THREAD

**Issue by Harvie** [SVG-Edit/svgedit#173] opened 2017-02-26 15:20 UTC
Not really sure what causes this.

```
Uncaught DOMException: Blocked a frame with origin "https://wiki.spoje.net" from accessing a cross-origin frame.
    at https://cdn.rawgit.com/SVG-Edit/svgedit/stable/editor/embedapi.js:150:64
```

This should be ok, because cdn.rawgit.com sends `Access-Control-Allow-Origin: *` header. But it's still not working. I don't know why. If i also send this header from my site nothing changes. Maybe there's bug in browser? Have anybody run into same issues with svgedit linked from cdn?

**Comment by brettz9** [comment] 2018-05-31 09:17
I might also mention that it is necessary to include the following extension (assuming it can be fixed):

`editor/extensions/ext-xdomain-messaging.js`

**Comment by brettz9** [comment] 2018-07-19 05:50
This is now fixed in `master` (6122d6d2f1feae354ff6c8d69856db8d7e472ab9). Currently, you must not only ensure that `Access-Control-Allow-Origin` is set to accept your origin but also that the likes of the following is added to the embedded editor:

```js
svgEditor.setConfig({
  allowedOrigins: ['*'] // Or specific whitelisted origin(s)
});
```

If you target the file `xdomain-svg-editor-es.html`, this config is added there by default, assuming the file is of course present on your targeted server and has not been changed. This will allow it to receive messages from the specified origin and will attempt to post back responses to it.

As demonstrated in `embedapi-dom.js` (used by `embedapi.html`), the second argument to the `EmbeddedSVGEdit` constructor must be passed the precise allowed origin (or `*`) in an array of allowed origins. This is to ensure the *embedding* editor also restricts the origin of the messages it can receive (back) (albeit as responses to the messages it initiates).

Closing, but feel free to reopen if you have issues or questions on getting it to work.

**Comment by brettz9** [comment] 2018-10-23 12:13
One important limitation I should mention, however, is that Chrome does not allow `localStorage`, which we use for the clipboard and any local storing of the image. While we are avoiding throwing some such errors now, there are a few I see I missed, and more significantly, we should add a meaningful workaround; I think we should report a message back to the opening frame so it can do (and supply) its own storage when needed.

I'm therefore reopening until we may handle this.

**Comment by brettz9** [comment] 2018-10-23 12:19
You may see it in action, btw, at https://svg-edit.github.io/svgedit/releases/latest/editor/embedapi.html .

**Comment by brettz9** [comment] 2018-10-24 07:12
I've since made a few more fixes... localStorage doesn't work (including how we use it for clipboard), but other features work...

**Comment by jfhenon** [comment] 2021-08-16 08:36
V7 has been redesigned to allow svgEdit to fit in a div. This provides a tighter integration. The above issue would not be  relevant so the issue is closed.

**Closed by jfhenon** 2021-08-16 08:36 UTC
Labels: bug, wontfix
