### ISSUE TITLE
Chrome is unusable when selecting lots of paths

### ISSUE THREAD

**Issue by codedread** [SVG-Edit/svgedit#26] opened 2015-11-29 16:37 UTC
Open SVG-edit with the SVG file pasted below and then drag-select a bunch of the paths.  You can see that Chrome has a hard time rendering the select boxes and keeping up with the mouse.  No similar problem exists in Firefox which keeps up just fine.
# 

<svg width="500" height="500" xmlns="http://www.w3.org/2000/svg" xmlns:svg="http://www.w3.org/2000/svg">
 
 <g stroke="null">
  <title>Features</title>
  <path stroke="#000000" fill="none" stroke-width="2" d="m148.72322,202.77881c3.67596,-7.00858 4.05699,-8.48969 7.73283,-15.49817c4.82916,-5.13416 10.29091,15.0087 12.77013,22.47559" id="svg_18"/>
  <path stroke="#000000" fill="none" stroke-width="2" d="m134.34709,188.39349c2.60612,-9.00548 4.22293,-15.91933 9.37553,-22.53543c5.15273,-6.61609 7.35718,15.71062 10.2251,23.18295" id="svg_7"/>
  <path stroke="#000000" fill="none" stroke-width="2" d="m136.16826,164.55119c1.1557,-5.18611 3.70772,-8.86615 7.38377,-15.87468c4.82896,-5.13423 10.29083,15.00858 12.77013,22.47551" id="svg_9"/>
  <path stroke="#000000" id="svg_5" fill="none" stroke-width="2" d="m130.94594,204.61511c3.67603,-7.00833 9.60486,-25.04381 14.08055,-16.27576c4.47578,8.76801 2.61897,14.25388 6.4225,23.25299"/>
  <path stroke="#000000" fill="none" stroke-width="2" d="m152.97641,175.37897c3.67586,-7.00858 4.05688,-8.48958 7.73283,-15.49817c4.82898,-5.13432 10.29091,15.00867 12.77014,22.47546" id="svg_8"/>
  <path stroke="#000000" fill="none" stroke-width="2" d="m150.13936,156.1627c3.67606,-7.00853 4.05699,-8.48958 7.73294,-15.49815c4.82898,-5.13428 10.29082,15.00871 12.77002,22.47554" id="svg_10"/>
  <path stroke="#000000" fill="none" stroke-width="2" d="m168.68434,166.18129c3.67595,-7.00853 4.0569,-8.4897 7.73285,-15.49821c4.82907,-5.13431 10.29094,15.00853 12.77016,22.47537" id="svg_11"/>
  <path stroke="#000000" id="svg_6" fill="none" stroke-width="2" d="m205.0256,137.67624c3.6759,-7.00862 4.05692,-8.48962 7.73285,-15.49835c4.8291,-5.13411 10.29095,15.00867 12.77005,22.47548"/>
  <path stroke="#000000" fill="none" stroke-width="2" d="m216.67606,92.73186c-2.45419,-3.70404 -2.69266,-4.47987 -5.14682,-8.18393c-3.30978,-2.7504 -7.60007,7.6183 -9.5123,11.45415" id="svg_39"/>
  <path stroke="#000000" id="svg_13" fill="none" stroke-width="2" d="m194.38721,115.84761c3.6759,-7.00873 4.05688,-8.48973 7.73282,-15.49831c4.82913,-5.13412 10.29089,15.0087 12.77014,22.47536"/>
  <path stroke="#000000" fill="none" stroke-width="2" d="m189.23273,144.93457c2.86975,-7.40543 3.08279,-8.92207 5.95258,-16.32764c4.22498,-5.68558 11.90253,13.64261 15.2005,20.75206" id="svg_17"/>
  <path stroke="#000000" fill="none" stroke-width="2" d="m164.20309,147.66077c5.39839,-10.29269 5.95789,-12.46753 11.35617,-22.76022c7.09175,-7.53992 15.11285,22.04138 18.75372,33.00671" id="svg_12"/>
  <path stroke="#000000" id="svg_14" fill="none" stroke-width="2" d="m221.53101,130.08604c3.67593,-7.00848 4.05679,-8.4895 7.73282,-15.49803c4.8291,-5.13428 10.29086,15.00858 12.77011,22.47531"/>
  <path stroke="#000000" fill="none" stroke-width="2" d="m252.53738,119.94174c3.67596,-7.00867 4.05692,-8.48962 7.73288,-15.49823c4.8291,-5.13429 10.2908,15.00868 12.77002,22.47539" id="svg_34"/>
  <path stroke="#000000" fill="none" stroke-width="2" d="m252.0069,59.41127c2.8374,-4.2672 3.12933,-5.16995 5.96677,-9.43725c3.7392,-3.12103 8.04279,9.18108 9.99158,13.74242" id="svg_36"/>
  <path stroke="#000000" fill="none" stroke-width="2" d="m259.95792,87.08681c3.67596,-7.00858 4.05688,-8.48962 7.73282,-15.4984c4.82916,-5.13402 10.29083,15.0088 12.77005,22.4756" id="svg_35"/>
  <path stroke="#000000" fill="none" stroke-width="2" d="m239.05927,99.37352c3.67593,-7.00835 4.05698,-8.48949 7.73279,-15.49802c4.82932,-5.13422 10.29086,15.00865 12.77017,22.47546" id="svg_33"/>
  <path stroke="#000000" id="svg_20" fill="none" stroke-width="2" d="m209.35367,110.6425c6.68887,-12.75301 7.38211,-15.44804 14.07104,-28.20078c8.78687,-9.34227 18.72534,27.31003 23.23669,40.89679"/>
  <path stroke="#000000" fill="none" stroke-width="2" d="m165.71919,115.79915c2.83745,-4.26738 3.12932,-5.16995 5.96667,-9.43719c3.73929,-3.12099 8.04288,9.18094 9.99161,13.74226" id="svg_38"/>
  <path stroke="#000000" fill="none" stroke-width="2" d="m180.1962,124.27328c3.67586,-7.00854 4.05692,-8.48961 7.73285,-15.49814c4.82913,-5.13432 10.2908,15.00879 12.77011,22.47556" id="svg_15"/>
  <path stroke="#000000" fill="none" stroke-width="2" d="m144.56628,228.48172c3.67604,-7.00858 9.60486,-25.04404 14.08057,-16.27588c4.4758,8.76801 2.61899,14.25378 6.4225,23.25308" id="svg_26"/>
  <path stroke="#000000" fill="none" stroke-width="2" d="m143.79399,260.17172c3.67596,-7.00858 9.60478,-25.04401 14.08057,-16.27579c4.4758,8.76804 2.61908,14.25391 6.42241,23.25317" id="svg_27"/>
  <path stroke="#000000" fill="none" stroke-width="2" d="m128.49568,242.01157c3.67593,-7.00836 9.60486,-25.04382 14.08055,-16.27582c4.47578,8.76816 2.61908,14.25375 6.4225,23.25302" id="svg_22"/>
  <path stroke="#000000" fill="none" stroke-width="2" d="m87.64987,265.83051c-2.44299,-4.35745 -2.67896,-5.27109 -5.12199,-9.62842c-3.30164,-3.23181 -7.62361,8.99377 -9.54773,13.5177" id="svg_42"/>
  <path stroke="#000000" fill="none" stroke-width="2" d="m86.35857,261.17676c3.6759,-7.0087 9.60474,-25.04413 14.08052,-16.27588c4.47578,8.76801 2.61899,14.25388 6.42241,23.25317" id="svg_24"/>
  <path stroke="#000000" fill="none" stroke-width="2" d="m119.25476,268.492c3.67586,-7.00858 9.60478,-25.04401 14.08055,-16.27579c4.47571,8.76794 2.61899,14.25369 6.42233,23.25299" id="svg_28"/>
  <path stroke="#000000" fill="none" stroke-width="2" d="m103.65144,248.14322c3.67601,-7.00854 9.60474,-25.04401 14.08063,-16.27594c4.47568,8.76819 2.61888,14.25397 6.42232,23.25314" id="svg_23"/>
  <path stroke="#000000" fill="none" stroke-width="2" d="m118.26764,195.03024c-2.44283,-4.35754 -2.679,-5.2709 -5.12202,-9.62854c-3.30139,-3.2317 -7.62361,8.99408 -9.54776,13.51782" id="svg_40"/>
  <path stroke="#000000" fill="none" stroke-width="2" d="m101.94829,231.44849c-2.44299,-4.35745 -2.67903,-5.27106 -5.12204,-9.62842c-3.30147,-3.23178 -7.62358,8.99377 -9.54767,13.51767" id="svg_41"/>
  <path stroke="#000000" fill="none" stroke-width="2" d="m98.34485,223.09976c3.67595,-7.00858 9.60487,-25.04401 14.08058,-16.27597c4.47566,8.76819 2.61896,14.25388 6.42241,23.2532" id="svg_25"/>
  <path stroke="#000000" fill="none" stroke-width="2" d="m115.46883,220.05466c3.67587,-7.00867 9.60478,-25.04391 14.08057,-16.27585c4.47569,8.7681 2.619,14.25375 6.42242,23.25317" id="svg_21"/>
  <path stroke="#000000" fill="none" stroke-width="2" d="m112.90187,184.77457c1.76805,-5.90698 5.02887,-9.94191 9.86702,-17.73328c6.01857,-5.51451 10.67798,18.32697 12.93161,27.20609" id="svg_16"/>
  <path stroke="#000000" fill="none" stroke-width="2" d="m137.50252,277.67395c3.67577,-7.00867 9.60469,-25.04407 14.08058,-16.27594c4.47577,8.76801 2.61888,14.25388 6.4223,23.25317" id="svg_29"/>
 </g>
</svg>

**Comment by ian-workcircle** [comment] 2015-11-30 17:39
Its not too bad for me (Firefox probably slower for me), but maybe I'm testing wrong. Is this with any shapes, or just paths and approx how many before its obvious that there's an issue ? Also wondering if its a particular Chrome version ?

**Comment by ibrierley** [comment] 2015-11-30 17:59
Sorry, logged in with wrong account, so redoing. Can you clarify how many paths and what type and browser ver is being used, as a few paths drag fine for me ?

For me its a lot slower in Firefox, and Chrome is ok (not saying its great, but I'm wondering if there are specific types of paths or filters etc that are making it worse). Wondering if its tied to certain versions or a general issue.

**Comment by codedread** [comment] 2015-12-01 03:27
I'm using Chrome Version 46.0.2490.86 (64-bit) on OSX (Yosemite).  Firefox 42.0 does just fine with it - Chrome's multiselect rubberbox really lags the mouse cursor.

I'm attaching the SVG file as a TXT file, since GitHub doesn't suport uploading SVG files.

[mountains.svg.txt](https://github.com/SVG-Edit/svgedit/files/48077/mountains.svg.txt)

**Comment by codedread** [comment] 2015-12-01 03:32
I counted them... 33 paths

**Comment by ibrierley** [comment] 2015-12-01 19:27
Yes, I can see its a bit slower on Chrome with those paths. Has a quick
peek, it seems to take quite a bit of time doing the transform replacement
for each path, but that could be a red herring.

I note if you group all the elements and drag thats quite fast (I guess not
surprising), but I assume that isn't desired normally as it can change the
order of elements in the DOM. Not sure of any suggestions how to make that
faster (if that is the problem).

**Comment by progers** [comment] 2015-12-03 07:14
This is due to O(n^2) behavior in updating the little preview window hidden in the layers panel. There are workarounds, but I'd like to fix the root cause in blink.

I've filed https://code.google.com/p/chromium/issues/detail?id=565120.

**Comment by codedread** [comment] 2015-12-03 07:19
Awesome debugging... if only we knew someone who worked on the Blink team...

**Comment by codedread** [comment] 2015-12-03 16:49
@progers what do you think about disabling the preview pane in Chrome until this is fixed?

**Comment by progers** [comment] 2015-12-03 18:48
That sounds reasonable. Would you be up for adding a chrome-specific (via browser sniffing) display:none on the <use> element?

**Comment by codedread** [comment] 2015-12-04 01:32
Sent in pull request #44

**Comment by codedread** [comment] 2015-12-04 01:32
(and it makes a huge difference!)

**Comment by codedread** [comment] 2015-12-04 01:37
I should also point out that #44 also makes editing large paths once again very quick.  I'm not sure why that would be unless the segment controls are also referenced in the <use> ?

Should we close this issue and open another one to track the Chrome fix and reverting #44?

**Comment by progers** [comment] 2015-12-04 01:49
Lets leave this open since it has all the context.

**Comment by codedread** [comment] 2015-12-04 05:28
So it occurred to me that the reason this is actually causing the problem is that the selectors themselves are being referenced by the <use>.  It seems that it might be possible to only reference the "svgcontent" <svg> element (instead of the "svgroot" element) in the overview pane.  Still a problem but not as bad since a selector generally doubles the # of elements in play...

**Comment by progers** [comment] 2015-12-04 05:36
That may be the case for moving the path but this bug surfaces elsewhere in svg-edit. I noticed double-clicking a path would lock the entire browser and ended up reducing it down to the same bug you reported. You can see the behavior in this demo where it takes several seconds to add 250 circle elements: http://jsbin.com/bobofopaxu

**Comment by progers** [comment] 2015-12-07 03:03
Fixed! https://chromium.googlesource.com/chromium/src.git/+/491876565010e0d7d4a036460188a66c2b34c946

Lets leave the workaround patch in for ~6 weeks (Chrome's release cycle) to give this a chance to roll out to all users.

**Comment by codedread** [comment] 2015-12-07 03:41
Cool - even better, can we sniff for the Chrome version and enable it?  Would Chrome 49 have the fix when it's released?

**Comment by progers** [comment] 2015-12-07 03:46
Yep! It'll be in Chrome 49.

According to https://dev.opera.com/blog/opera-user-agent-strings-opera-15-and-beyond, just sniffing the Chrome version should work (just fyi).

**Comment by mihailik** [comment] 2016-01-05 10:18
@progers the URL in your comment should have trailing slash, otherwise comes with error (bad bad Opera web site!)

**Comment by flintobrien** [comment] 2016-04-22 18:26
We've seen a problem in Chrome and Firefox; particularly when the top-level selections have matrix transforms. With a large SVG document (270 top-level elements), select-all takes over 1 minute. When there are a few elements, you don't see the problem.

Chrome's profiler points to the native getBBox() taking all the time. 

**The problems are due to:**

1) Both the thumbnail preview window and the prevalence of elements with matrix transforms (in our sample document). When getStrokedBBox/getCheckedBBox() sees a matrix transform, it calculates the BBox by enclosing a clone of the element and adding it to the DOM, calling getBBox(), then removing it. Without the transforms, there's no DOM change, so it's faster. If you delete the thumbnail and keep the transforms, it's faster, but still slow.

2) The various getBBox utility functions call the native getBBox() function multiple times for each element. It's at least 4 times for each top-level element when performing a rubber band selection.

3) svgcanvas: addToSelection() calls svgedit.utilities.getBBox(), throws the bbox away, then calls selectorManager.requestSelector() which calls svgedit.utilities.getBBox() again.

I've worked this week to refactor the related functions to calculate the BBox without updating the DOM and only call the native getBBox() once. I hope it's satisfactory. Stay tuned for some pull requests. GEC fork.

**Comment by codedread** [comment] 2016-04-22 18:39
Cool to hear, Flint.  Can you clarify what "GEC fork" means?

**Comment by flintobrien** [comment] 2016-04-22 19:12
Fork: [gec/svgedit](https://github.com/gec/svgedit)
I'm putting the performance improvements on branch getBBox-performance. I have things working, but I'm still adding tests and checking things in.

Our project branch is fisheye which has other enhancements specific to our project.

**Comment by flintobrien** [comment] 2016-04-25 15:48
See performance improvements pull request https://github.com/SVG-Edit/svgedit/pull/103

**Comment by brettz9** [comment] 2018-05-30 12:48
With PR #103 merged, it looks like this can be closed, though feel free to reopen and restate any remaining issues if not...

**Closed by brettz9** 2018-05-30 12:48 UTC
