### ISSUE TITLE
The rubberband box placement error

### ISSUE THREAD

**Issue by harikk** [SVG-Edit/svgedit#48] opened 2015-12-08 10:48 UTC
Issue: The rubberband box is not placed properly for imported SVG images in the editor
How to reproduce: Import an SVG image. click on the image. The rubber band box around the image is  not properly coming. its left and top is not coming properly.

**Comment by adrianbj** [comment] 2015-12-08 10:50
I think this is a duplicate of: https://github.com/SVG-Edit/svgedit/issues/5 - it least it's the same as I describe in my comment. To reiterate here, this is a new since 2.6, although not sure whether it existed in 2.7.

**Comment by ibrierley** [comment] 2015-12-08 11:33
This looks ok for me these days, I can remember the bug though previously. Is there a specific svg to test with (and which browser out of interest?).

**Comment by ibrierley** [comment] 2015-12-08 11:52
Just checking, I'm wondering if its related to this pull request I did a while back.. https://github.com/SVG-Edit/svgedit/pull/7 I don't think it went through as needing some documentation updating, but I'm not so good with git (happy to take advice on what to do here), and can't see how I amend an existing pull request.

**Comment by harikk** [comment] 2015-12-08 12:38
I tested by importing http://canvaschanger.project0884.com/sample/sample.svg to a new image canvas from https://svg-edit.github.io/svgedit/releases/svg-edit-2.8.1/svg-editor.html . It is the latest version, isn't it?

Can you try moving it more than once? thus the issue will happen.

**Comment by harikk** [comment] 2015-12-10 05:23
Also I tried applying #7 to my local copy, but still my issue is not resolved.

**Closed** 2016-01-16 20:35 UTC
