### ISSUE TITLE
multiselect and move of grouped object

### ISSUE THREAD

**Issue by sjernigan** [SVG-Edit/svgedit#341] opened 2019-04-19 16:02 UTC
**Describe the bug**
Moving a set of selected elements behaves differently if the "dragged element" is a group.  I think this is actually two closely related bugs.  Let me define the element that is clicked on to begin the move operation as the "dragged element".  First, selecting the group as the dragged element removes all other elements from the multiselect.  Selecting a non-group element works as intended.  Second, shift selecting the group as the dragged element preserves the multiselect but permanently makes the grouped element translate at an exaggerated rate.

**To Reproduce**
1. Draw three plain shapes (e.g., ovals) in a row. Let's call them A, B, and C.
2. Select and group B and C.
3. Select all three by drawing a box that includes them all with the select tool
4. Click on and drag A.  This should be the expected behavior.  All three images should translate and maintain their position relative to each other.
5. Click on and drag B or C.  A will be removed from the multiselect and only B & C will move.
6. Multiselect all three again.
7. Shift click and drag on B or C.  The multiselect is preserved but the relative position of B&C to A isn't preserved over the translation.
8. A normal click and drag on A continues the behavior in 7.

**SVG-Edit environment (IMPORTANT)**
-Version: 4.3.0

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Chrome
 - Version 73

**Comment by sjernigan** [comment] 2019-04-19 18:18
OK, so this bit of magic seems to come from svgcanvas.js:mousedown()
` 
case 'select':
    started = true;
    currentResizeMode = 'none';
    if (rightClick) { started = false; }

    if (mouseTarget !== svgroot) {
      // if this element is not yet selected, clear selection and select it
      if (!selectedElements.includes(mouseTarget)) {
        // only clear selection if shift is not pressed (otherwise, add
        // element to selection)
        if (!evt.shiftKey) {
          // No need to do the call here as it will be done on addToSelection
          clearSelection(true);
        }
        addToSelection([mouseTarget]);
        justSelected = mouseTarget;
        pathActions.clear();
      }
`
The group isn't included in selectedElements so it's as if you had clicked on another object not previously in the multiselect.  My first thought was that the "includes" was just too simplistic.  Maybe it should try to figure out that the group is included.  However, I think the real answer is that the group should have been in the selectedElements (and not the elements of it).  For instance, I can multiselect A and B without C.  That doesn't seem right.  I can even do an operation on that multiselect, (e.g., align-left), that will change the relative position of B to C.  That seems to break the notion of the group to me.  
Additionally, I think the weird shift-click behavior is because the group gets added to the selectedElements.  Now when you drag, the motion translation happens twice to B&C; once because of the group and once because of the individual elements.  The good news is that if the components of the group weren't in selectedElements, I think it'll work correctly.

**Comment by sjernigan** [comment] 2019-04-19 20:30
I think I have a fix.  It basically involves iteratively moving up the hierarchy in two locations when an element is selected that is in a group.  Both of these changes are in svgcanvas.js

After line 1807 add the following
>    // if this element is in a group, go up until we reach the top-level group
>     // just below the layer groups
>     while (mouseTarget && mouseTarget.parentNode && mouseTarget.parentNode.parentNode && mouseTarget.parentNode.parentNode.tagName === 'g') {
>      mouseTarget = mouseTarget.parentNode;
>    }

Replace line 2221 with
>  var intElem = newList[i];
>
>    // if this element is in a group, go up until we reach the top-level group
>    // just below the layer groups
>    // TODO: once we implement links, we also would have to check for <a> elements
>     while (intElem && intElem.parentNode && intElem.parentNode.parentNode && intElem.parentNode.parentNode.tagName === 'g') {
>        intElem = intElem.parentNode;
>    }

Sorry this isn't in the form of a PR.  My version is quite hacked up due to local requirements and I don't fully understand your build process.

**Comment by brettz9** [comment] 2019-04-20 03:13
Help us make the build process more clear in the docs then. I'll summarize below, but let me know what isn't clear if you would.

For PRs, you should work on the ES source, testing first in `svg-editor-es.html` in a modern browser and work on relevant source files. If it is all good in there, you can run `npm run browser-test` which will run all of the necessary build processes and a test file (`npm test` is set to do some UI tests, as the preferred way of testing going forward, but there is very little there atm).

Note that it may take a while to run all of the ESLinting (which has been slowed down recently by the compat plugin which does a lot of checking for browser compatibility) and for the Rollup scripts building the various dist formats.

**Comment by jfhenon** [comment] 2021-10-05 22:39
I could not reproduce. Would you please confirm this is fixed?

**Comment by jfhenon** [comment] 2022-01-01 17:06
I tested again and it works with 7.1.x so I assume we can close the issue

**Closed by jfhenon** 2022-01-01 17:06 UTC
Labels: bug - unconfirmed
