### ISSUE TITLE
Editor converts imported icon path in a wrong way.

### ISSUE THREAD

**Issue by onlymega** [SVG-Edit/svgedit#116] opened 2016-05-21 09:40 UTC
This svg icon looks fine when opened in browser but when imported to editor looks broken:

`<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 100 100"><g transform="scale(3.5714285714285716)" id="picture"><path d="M7 0H1C.4 0 0 .4 0 1v6c0 .6.4 1 1 1h6c.6 0 1-.4 1-1V1c0-.6-.4-1-1-1zM6 6H2V2h4v4zm11-6h-6c-.6 0-1 .4-1 1v6c0 .6.4 1 1 1h6c.6 0 1-.4 1-1V1c0-.6-.4-1-1-1zm-1 6h-4V2h4v4zm11-6h-6c-.6 0-1 .4-1 1v6c0 .6.4 1 1 1h6c.6 0 1-.4 1-1V1c0-.6-.4-1-1-1zm-1 6h-4V2h4v4zM7 10H1c-.6 0-1 .4-1 1v6c0 .6.4 1 1 1h6c.6 0 1-.4 1-1v-6c0-.6-.4-1-1-1zm-1 6H2v-4h4v4zm11-6h-6c-.6 0-1 .4-1 1v6c0 .6.4 1 1 1h6c.6 0 1-.4 1-1v-6c0-.6-.4-1-1-1zm-1 6h-4v-4h4v4zm11-6h-6c-.6 0-1 .4-1 1v6c0 .6.4 1 1 1h6c.6 0 1-.4 1-1v-6c0-.6-.4-1-1-1zm-1 6h-4v-4h4v4zM7 20H1c-.6 0-1 .4-1 1v6c0 .6.4 1 1 1h6c.6 0 1-.4 1-1v-6c0-.6-.4-1-1-1zm-1 6H2v-4h4v4zm11-6h-6c-.6 0-1 .4-1 1v6c0 .6.4 1 1 1h6c.6 0 1-.4 1-1v-6c0-.6-.4-1-1-1zm-1 6h-4v-4h4v4zm11-6h-6c-.6 0-1 .4-1 1v6c0 .6.4 1 1 1h6c.6 0 1-.4 1-1v-6c0-.6-.4-1-1-1zm-1 6h-4v-4h4v4z"/></g></svg>`

Please note that this is a one path icon (so the problem is in path conversion/normalization inside the editor).

**Comment by codedread** [comment] 2016-05-21 17:56
This seems to be because of the following function:

fixEnd: function(elem) {
    // Adds an extra segment if the last seg before a Z doesn't end
    // at its M point
    ...
}

I'm not sure why we are doing that, but adding the extra line segments is where I think the path parsing is screwing up.

**Comment by onlymega** [comment] 2016-05-26 19:29
It seems that this issue affects all icons that have a few separate shapes combined into one path. 
Can you please tell me what is the "fixEnd" function for and is it safe to remove it from the editor?

**Comment by vbarbarosh** [comment] 2016-05-28 19:15
It seems that the issue is in [the following lines](https://github.com/SVG-Edit/svgedit/blob/master/editor/svgutils.js#L1297):

```javascript
case 5: // relative line (l)
case 3: // relative move (m)
    // If the last segment was a "z", this must be relative to
    if (last_m && segList.getItem(i-1).pathSegType === 1 && !toRel) {
        curx = last_m[0];
        cury = last_m[1];
    }
```
After commenting them the image displays correctly.
```javascript
case 5: // relative line (l)
case 3: // relative move (m)
    // If the last segment was a "z", this must be relative to
    if (last_m && segList.getItem(i-1).pathSegType === 1 && !toRel) {
        // curx = last_m[0];
        // cury = last_m[1];
    }
```

**Comment by brettz9** [comment] 2018-05-31 00:41
I am seeing no issue with this file (Chrome 66 or Firefox 61.0b9) in our [pre-release](https://svg-edit.github.io/svgedit/releases/svg-edit-3.0.0-alpha.4/editor/svg-editor.html), and the discussed problematic code seems to have since been changed significantly, so closing.

Feel free to reopen or comment further if the issue still remains and you can reproduce.

**Closed by brettz9** 2018-05-31 00:41 UTC
