### ISSUE TITLE
import image without size

### ISSUE THREAD

**Issue by jyy1082** [SVG-Edit/svgedit#221] opened 2018-03-16 02:35 UTC
The imported image does not have size specification using master code. It will show a really small pot after import a image, it is too small to drag to change the size. Is there anyone have the same issue?
![image](https://user-images.githubusercontent.com/8751908/37500678-2e853270-28a1-11e8-8457-4243fb0d2fb2.png)

**Comment by brettz9** [comment] 2018-05-30 09:42
I have confirmed this issue can occur in the case when an SVG file does not have a namespace. Please let us know if adding the SVG namespace to the root `<svg>` element fixes the issue for you.

I've filed #250 to try to support non-namespaced SVG.

**Comment by brettz9** [comment] 2018-06-12 00:08
Closing due to lack of a response (and due to a new issue already looking at the confirmed portion of this issue).

**Closed by brettz9** 2018-06-12 00:08 UTC
Labels: reply needed
