### ISSUE TITLE
crashed when loads more svg element (file size is 844kb)

### ISSUE THREAD

**Issue by sivasaravanand** [SVG-Edit/svgedit#234] opened 2018-05-15 13:15 UTC
[XMLFile1.txt](https://github.com/SVG-Edit/svgedit/files/2005102/XMLFile1.txt)

Hi,

When i upload this file into svg editor and browse responding very slow and in few mins editor got crashed.

Please guide me how to handle this type of file.

Thanks,
Shiva

**Comment by brettz9** [comment] 2018-05-30 09:04
While I was able to confirm (in Chrome 66 and Firefox 61.0b9), that this file indeed has performance issues, if it is not due to the file size, we'd want this isolated to particular features which are causing the slow-down.

Closing now, as the scope is rather wide, but feel free to reopen if you are able to find our handling of particular SVG elements (or what not) can create reproducible performance problems, in which case we can look into whether that particular feature can somehow be optimized on our end.

**Closed by brettz9** 2018-05-30 09:04 UTC
