### ISSUE TITLE
fix svg xmlns attribute

### ISSUE THREAD

**Issue by ewwink** [SVG-Edit/svgedit#322] opened 2019-01-30 13:53 UTC
On the net I see a lot SVG without `xmlns` atribute but this tool not accept it, for example if I insert this code (keyboard `U`)

```svg
<svg width="400" height="400">
  <path d="m120.4 246.6l96.5-168.9 96.5 168.9 -193 0z" />
</svg>
```

I get this error

```
There were parsing errors in your SVG source.
 
Revert back to original SVG source?
```

I know I can fix it by adding `xmlns="http://www.w3.org/2000/svg"` but can this tool automaticaly fix it?

**SVG-Edit environment (IMPORTANT)**
- https://svg-edit.github.io/svgedit/releases/latest/editor/svg-editor.html

**Comment by brettz9** [comment] 2019-01-30 14:03
This is a dupe of #250 . I've updated its description to make reference of the `xmlns` (i.e., XML namespace) declaration for easier discovery.

**Closed by brettz9** 2019-01-30 14:03 UTC
