### ISSUE TITLE
Sometimes open new SVG doesn't complete.

### ISSUE THREAD

**Issue by ibrierley** [SVG-Edit/svgedit#4] opened 2015-07-06 17:00 UTC
On Chrome 42.0.2311.135 (64-bit), if I select 'open svg' it seems to load in the svg, but continues to say 'loading image, please wait'. It doesn't seem to do this in Opera

**Comment by brettz9** [comment] 2018-05-30 12:55
Do you still get this for the files you want to open on our current pre-release: https://svg-edit.github.io/svgedit/releases/svg-edit-3.0.0-alpha.4/editor/svg-editor.html ?

**Comment by mindplay-dk** [comment] 2020-02-19 13:41
I had this problem while trying to open this file from Wikimedia:

https://upload.wikimedia.org/wikipedia/commons/b/b4/Flag_of_Anguilla.svg

**Comment by mindplay-dk** [comment] 2020-02-19 13:46
Oddly, after killing the tab and reopening, it opens up with the image already open - this only happens when trying to directly open the file from the menu.

To recreate the problem, download the file from Wikimedia - open Chrome in incognito mode, then open the file via "Open SVG" in the menu. It consistently hangs. After a few a moment, reload the tab (and confirm that you want to stop the running script) and the image then opens without problems.

**Comment by jfhenon** [comment] 2021-06-06 18:49
I could not reproduce the issue using the latest version https://svgedit.netlify.app/editor/index.html and chrome 91.0.4472.77.
I close the issue but please open a new issue if you can reproduce it.
Thanks

**Closed by jfhenon** 2021-06-06 18:49 UTC
Labels: bug - unconfirmed

**Comment by mindplay-dk** [comment] 2021-06-13 11:25
Confirmed: working in the current version. 🙂👍
